#install.packages("xlsx")
#library(xlsx)
#dataXml <- read.xlsx("answers.xlsx")
#install.packages("dplyr")
library(dplyr)
dataCsv <- read.csv("answers.csv")
columnName <- colnames(dataCsv)
boxplot(dataCsv[1:10, 3:ncol(dataCsv)], col = rainbow(10))# строим коробку с усами определяем медиану, нижний ус, первый квартиль, третитий квартиль, и верхний ус
hist(dataCsv$Бегущий.по.лезвию.2049, breaks = 10) #строим гистограммы определяем моды по ним
hist(dataCsv$Драйв, breaks = 10)
hist(dataCsv$Игра.на.понижение, breaks = 10)
hist(dataCsv$Ла.Ла.Ленд, breaks = 10)
hist(dataCsv$Дневник.памяти, breaks = 10)
hist(dataCsv$Славные.парни, breaks = 10)
hist(dataCsv$Место.под.соснами, breaks = 10)
hist(dataCsv$Эта.дурацкая.любовь, breaks = 10)
hist(dataCsv$Фанатик, breaks = 10)
hist(dataCsv$Ларс.и.настоящая.девушка, breaks = 10)
arrange(dataCsv[1:10, 3:ncol(dataCsv)], mean(dataCsv$Бегущий.по.лезвию.2049))
